auto commit

diff --git a/git-upstream b/git-upstream
--- a/git-upstream
+++ b/git-upstream
@@ -232,7 +232,10 @@ git_branch_default_upstream_ref()
 }
 git_branch_default_upstream()
 {
-    git_branch_default_upstream_ref "$@" | sed 's/^refs\/heads\///'
+    git rev-parse --abbrev-ref --symbolic-full-name "$1"@{upstream}
+
+    # OR
+    # git_branch_default_upstream_ref "$@" | sed 's/^refs\/heads\///'
 }
 git_branch_exist()
 {
@@ -422,6 +425,38 @@ git_tree_add_blob()
     } | git mktree
 }
 
+git_workdir_save()
+{
+    local index_hash=$(git write-tree)
+
+    # add modified file to index and read index tree
+    git add -u
+    local working_hash=$(git write-tree)
+
+    # restore index tree
+    git read-tree $index_hash
+
+    echo $index_hash $working_hash
+}
+git_workdir_load()
+{
+    local index_hash=$1
+    local working_hash=$2
+
+    git_object_type $index_hash || die "invalid index hash: $index_hash"
+    git_object_type $working_hash || die "invalid workdir hash: $working_hash"
+
+    # First create a temp commit to restore working tree.
+    #
+    # git-read-index to index and git-reset does not work because deleted file in
+    # index does not apply to working tree.
+
+    local working_commit=$(echo "x" | git commit-tree $working_hash) || die get working commit
+    git reset --hard $working_commit || die reset to tmp commit
+    git reset --soft ORIG_HEAD || die reset to ORIG_HEAD
+    git read-tree $index_hash || die "load saved index tree from $index_hash"
+}
+
 git_copy_commit()
 {
     git_commit_copy "$@"
@@ -586,6 +621,11 @@ main()
             ;;
     esac
 
+    if git_branch_exist git-upstream-config-branch; then
+        :
+    else
+        die no branch git-upstream-config-branch
+    fi
 
     git show git-upstream-config-branch:.gitupstream \
     | while read name url; do
@@ -600,13 +640,24 @@ main()
 init()
 {
     local conf_fn=./.gitupstream
+    local br=git-upstream-config-branch
 
-    git checkout --orphan git-upstream-config-branch || die 'can not create branch'
-    git rm --cache -r -f .
-    git rm -r -f .
+    if git_branch_exist $br; then
+        :
+    else
+        git checkout --orphan $br || die 'can not create branch'
+
+        git reset .
+
+        echo "# remote url" > $conf_fn
+        git add $conf_fn
+        git commit $conf_fn -m 'init git-upstream-config-branch'
+    fi
+
+    git checkout $br || die checkout $br
+
     vim "$conf_fn"
-    git add "$conf_fn"
-    git commit -m 'init git-upstream-config-branch'
+    git commit $conf_fn -m 'update git-upstream-config-branch'
 }
 
 usage()
